spring:
  application:
    name: fraud-rule-engine
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false

app:
  security:
    secure-profile:
      username: ${FRAUD_ENGINE_SECURE_USER:secure-user}
      password: ${FRAUD_ENGINE_SECURE_PASSWORD:change-me-secure}
      role: ${FRAUD_ENGINE_SECURE_ROLE:API_CLIENT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: secure

management:
  endpoint:
    health:
      show-details: when_authorized
      roles: ${FRAUD_ENGINE_SECURE_ROLE:API_CLIENT}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{requestId:-no-request-id}] --- [%15.15t] %logger{36} : %msg%n"
